server:
  port: 4000

spring:
  application:
    name: colacode-oss
  config:
    import:
      - 'optional:nacos:common-redis.yaml'
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:10.0.20.25:8848}}
        namespace: ${NACOS_NAMESPACE:${SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE:dev}}
        group: ${NACOS_GROUP:${SPRING_CLOUD_NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}}
      config:
        server-addr: ${NACOS_SERVER_ADDR:${SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR:10.0.20.25:8848}}
        namespace: ${NACOS_NAMESPACE:${SPRING_CLOUD_NACOS_CONFIG_NAMESPACE:dev}}
        group: ${NACOS_GROUP:${SPRING_CLOUD_NACOS_CONFIG_GROUP:DEFAULT_GROUP}}
        import-check:
          enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

storage:
  type: local
  local:
    path: ./uploads/
    access-url: http://localhost:4000/oss/download/
  minio:
    endpoint: http://117.72.14.166:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: colacode