CREATE TABLE IF NOT EXISTS interview_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    interview_type VARCHAR(32) NOT NULL,
    post_type VARCHAR(64) NOT NULL,
    difficulty_level INT DEFAULT 1,
    engine_type VARCHAR(32) NOT NULL,
    source_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_question_no INT DEFAULT 0,
    total_question_count INT DEFAULT 0,
    total_score DECIMAL(5,2) DEFAULT 0,
    report_id BIGINT NULL,
    start_time DATETIME NULL,
    end_time DATETIME NULL,
    duration_seconds INT DEFAULT 0,
    version INT DEFAULT 0,
    is_deleted TINYINT DEFAULT 0,
    created_by VARCHAR(64),
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_by VARCHAR(64),
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interview_question_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    question_id BIGINT NULL,
    question_source VARCHAR(32) NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    category VARCHAR(64),
    difficulty INT DEFAULT 1,
    stem TEXT NOT NULL,
    standard_answer TEXT,
    rubric_id BIGINT NULL,
    round_no INT DEFAULT 1,
    parent_record_id BIGINT NULL,
    is_follow_up TINYINT DEFAULT 0,
    key_words VARCHAR(255),
    user_answer TEXT,
    rule_score DECIMAL(5,2) DEFAULT 0,
    ai_score DECIMAL(5,2) DEFAULT 0,
    final_score DECIMAL(5,2) DEFAULT 0,
    hit_keywords TEXT,
    miss_keywords TEXT,
    wrong_points TEXT,
    evaluation_comment TEXT,
    ask_time DATETIME NULL,
    answer_time DATETIME NULL,
    cost_seconds INT DEFAULT 0,
    status VARCHAR(32),
    is_deleted TINYINT DEFAULT 0,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interview_report (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    total_score DECIMAL(5,2) DEFAULT 0,
    base_score DECIMAL(5,2) DEFAULT 0,
    logic_score DECIMAL(5,2) DEFAULT 0,
    expression_score DECIMAL(5,2) DEFAULT 0,
    engineering_score DECIMAL(5,2) DEFAULT 0,
    summary TEXT,
    weakness_tags_json JSON,
    advantage_tags_json JSON,
    suggestion TEXT,
    recommended_practice_json JSON,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interview_rubric (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    post_type VARCHAR(64) NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    category VARCHAR(64) NOT NULL,
    total_score DECIMAL(5,2) DEFAULT 10,
    scoring_items_json JSON NOT NULL,
    version INT DEFAULT 1,
    enabled TINYINT DEFAULT 1,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);